### ISSUE TITLE
Secure vault password retrieval is not working for proxy-services. 

### ISSUE THREAD

**Issue by veneerac** [wso2/api-manager#1135]
### Description

Password retrieval from a secure vault does not resolve encrypted passwords for proxy services.
When the proxy service in wso2 EI or APIM secure vault is configured, encrypted passwords are not resolved.

### Steps to Reproduce

1 Create proxy service 
for EI
https://docs.wso2.com/display/EI640/Working+with+Proxy+Servers
for APIM
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/configuring_proxy_servers/

2 Configure the secure vault 
for EI
https://docs.wso2.com/display/EI660/Encrypting+Passwords+with+Cipher+Tool
for APIM
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords/

3 Invoke the service via proxy server.We can see the Authorization: Basic when we enable the wire logs clearly, and when we decode the based 64, we can confirm that it was not resolved by the secure vault. 

### Affected Component

Analytics

### Version

wso2ei-6.6.0, wso2apim-4.1.0

**Comment by malakaganga** [comment]
Hi @tdkmalan , @veneerac , @rmsamitha

I have added a draft fix for this issue after analyzing/debugging the code base.

https://github.com/wso2-support/wso2-synapse/pull/1996/files

Please create a patch ticket for this
Also when doing that please mention the following:
In cipher-tool.properties file please add the following entry

axisconfig.transportSender.profile.proxyPassword=conf/axis2/axis2.xml//axisconfig/transportSender[@name='http']/parameter[@name='proxyProfiles']/profile/proxyPassword,false

Also in this issue we are using proxy profiles and it is solved by above pr but

in ProxyConfigBuilder class in build() method direct TransportParams are still not resolved line: 108-109
Please mention that as well since I have already imported the resolver it would be a easy task.

Thanks,
Malaka
