### ISSUE TITLE
When an api move to "Created" state using "Demote to created" option still can invoke from old keys

### ISSUE THREAD

**Issue by BathiyaL** [wso2/api-manager#1144]
### Description

When an api is move to "Created" state using "Demote to created" option still can invoke from old keys, 
Since now API is in "CREATED" state and not even listed in the devprotal it should not be able to invoke using old keys.

### Steps to Reproduce

1. Create an API and Publish
2. Generate API key and make sure successful invocation (in CURL or Postman)
3. now go to Publisher and Lifecycle and click on "Demote to Created" 
4. Make sure now API s in "Created" state and also not listed on devportal 
5. Invoke api again with same key used in step 2

**Actual result** 
We can still invoke the API even its in the "CREATED" state
<img width="1255" alt="Screenshot 2022-12-15 at 16 48 44" src="https://user-images.githubusercontent.com/15939220/207846353-b8f9d7d5-b67a-4a72-bb83-944eb8875c32.png">

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

https://cplb.apim.com/

**Comment by chamilaadhi** [comment]
Probably due to the logic in https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayJMSMessageListener.java#L226 . Here we only remove API from the gateway maps if the state is RETIRED. For created state we could try removing the API as well

**Comment by Tharsanan1** [comment]
Hi, 

Based on the discussion with @tgtshanika  and @dushaniw, This is the expected behavior from v4.0.0 version onwards. When we demote the API from 'Published' to 'Created' state, the API is removed from the Devportal to prevent new subscriptions to the API but the already existing subscriptions can access the API without any issues. If the admin needs to block all API invocations to this API, the admin has to undeploy the API from the gateway.
