### ISSUE TITLE
Traffic Manager profile is not starting up with an osgi issue

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1148]
### Description

The profile optimized traffic manager profile does not startup with the following osgi errors after the xmlsec upgrade.

<img width="1507" alt="Screen Shot 2022-12-16 at 7 36 10 AM" src="https://user-images.githubusercontent.com/8557410/208030514-6fe44a36-786e-4cd2-adbb-70c5ef4f95db.png">
<img width="1512" alt="Screen Shot 2022-12-16 at 7 45 25 AM" src="https://user-images.githubusercontent.com/8557410/208030523-e390f154-dbdb-4440-b3b0-12dbb3f53577.png">

### Steps to Reproduce

Start the traffic manager profile after profile optimization.

### Affected Component

APIM

### Version

4.2.0-SNAPSHOT

**Comment by msm1992** [comment]
**Status Update**

- It was identified that the issue was occuring due to xmlsec 2.3.0 being unresolved.
```
osgi> b 121
org.apache.santuario.xmlsec_2.3.0 [121]
  Id=121, Status=INSTALLED   Data Root=/Users/sachini/wso2/gitclones/product-apim/modules/distribution/product/target/wso2am-4.2.0-SNAPSHOT/repository/components/traffic-manager/configuration/org.eclipse.osgi/121/data
  "No registered services."
  No services in use.
``` 

- This was due to an unresolved requirement on javax.xml.crypto which in default profile was exported from jsr105_1.0.1.wso2v1.jar
```
osgi> diag 121
org.apache.santuario.xmlsec [121]
  Unresolved requirement: Import-Package: org.apache.xml.dtm; version="[2.7.0,3.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xml.utils; version="[2.7.0,3.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xpath; version="[2.7.0,3.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xpath.compiler; version="[2.7.0,3.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xpath.functions; version="[2.7.0,3.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xpath.objects; version="[2.7.0,3.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: javax.xml.crypto
```

- This jsr105_1.0.1.wso2v1.jar is not included in the traffic manager profile's bundles.info. After manually updating the bundles.info to include below line the issue got resolved.
```
jsr105,1.0.1.wso2v1,../plugins/jsr105_1.0.1.wso2v1.jar,4,true
```

- Then we had a short call(Attendees: ChamilaA, Tharika, Sachini) to discuss how this should be fixed on the product side. And below options were suggested as possible solutions.
   - Option 1 : jsr105,1.0.1.wso2v1 is coming from org.wso2.carbon.identity.xacml.server.feature.group which is not included in the traffic-manager profile. Include it in traffic-manager profile and see if the issue is solved. 
   -  Option 2 : Include jsr105 1.0.1.wso2v1 as a import bundle def in carbon.apimgt.core feature

- Option 2 did not resolve the issue.
Option 1 resolved the issue but it introduced below new components(apart from jsr) into traffic manager profile.
```
org.wso2.carbon.identity.entitlement,5.24.4,../plugins/org.wso2.carbon.identity.entitlement_5.24.4.jar,4,true
org.wso2.carbon.identity.entitlement.common,5.24.4,../plugins/org.wso2.carbon.identity.entitlement.common_5.24.4.jar,4,true
org.wso2.carbon.identity.authenticator.thrift,5.24.4,../plugins/org.wso2.carbon.identity.authenticator.thrift_5.24.4.jar,4,true
org.wso2.balana,1.2.13,../plugins/org.wso2.balana_1.2.13.jar,4,true
libthrift,0.12.0.wso2v1,../plugins/libthrift_0.12.0.wso2v1.jar,4,true
```
