### ISSUE TITLE
Changes in the settings files of all portals does not get reflected

### ISSUE THREAD

**Issue by DinithHerath** [wso2/api-manager#1184]
### Description

- When there is a config change in the settings.json/settings.js file it is not get reflected in the tsx code. 
- Hence the default configuration values will be always fetched from the respective files

### Steps to Reproduce

1. Make a config change in the settings file such as change the value throttling policy count. The config should need to be used in a tsx file.
2. Then check whether the specific value is applied in the api call. Throttling policy limit as of the example of above.

### Affected Component

APIM

### Version

4.2.0, 4.1.0

**Comment by chanaka3d** [comment]
4.1.0 Issue is fixed with the following PR: https://github.com/wso2/apim-apps/pull/417. The PR contains the changes from the dependency update, but for this issue, the import changes are required for this fix.

https://github.com/wso2/apim-apps/pull/417/files#diff-f2a7c965a0658075a6170602f91e11c62fee647f0e6b85c54044d5fe185dd94dL22

**Comment by YasasRangika** [comment]
closing this issue as per the master branch fix: https://github.com/wso2/apim-apps/pull/417 has already been merged to the master branch.
