### ISSUE TITLE
Add application, api and enduser information to the warn log in authentication handler (Only if they are available)

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1205]

**Comment by chamikasudusinghe** [comment]
Date: 23rd January 2023

Update: The issue was reproduced in the alpha pack, both as admin and after scope assignment. During these two scenarios the return values from the messageContext is different. This has to be handled accordingly.

In terms of providing the request uri, it is available in the error that is popped after providing an invalid token when executing an API.

Steps to Reproduce

1. Create an API & Deploy in Publisher Portal
2. Create an Application in Dev Portal
3. Try out the API
4. Try out the API with an incorrect token

**Comment by chamikasudusinghe** [comment]
Date: 24rd January 2023

Update: The above solution can be provided in a very specified scenario where the JWT tokens are replaced with the default tokens. When we try to invoke an API without scope assignment, this warning is triggered and we can provide the requested logs. In other scenarios, when the warning is triggered, since we are using JWT, we do not get the application details since the token invalidation happens before getting the application name.

Considering the above scenario the fix was done and is now being tested with the master branch.

**Comment by chamikasudusinghe** [comment]
Date: 25th January 2023

Update: Tested the fix against 4.1 since the dev portal of the pack created from the master branch is not loading due to another issue. For the product, both carbon-apimgt and product-apim were built without an issue.

Master PR: https://github.com/wso2/carbon-apimgt/pull/11808
