### ISSUE TITLE
[4.2.0][Dependency Upgrade] poi version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1256]
### Description

This issue is created to track the progress in upgrading apache poi version in MI 4.2.0.

### Affected Component

MI

### Version

4.2.0

**Comment by RakhithaRR** [comment]
Ran into several issues while trying to upgrade apache poi to the latest version. It seems that the existing orbit bundles (`5.2.3.wso2v1`) for `poi` and `poi-ooxml` are missing several other requirements. However, there were some other issues even after adding those requirements.

There has been a separate effort to upgrade this previously in https://github.com/wso2/api-manager/issues/964. We are putting this issue on hold for the time being due to the concerns in the mentioned ticket.
