### ISSUE TITLE
testSetScopeToResourceTestCase failure

### ISSUE THREAD

**Issue by rmsamitha** [wso2/api-manager#1293]
### Description

Below test is failing in jenkins [1]
org.wso2.am.integration.tests.other.APIScopeTestCase.testSetScopeToResourceTestCase

Error log:
`org.wso2.am.integration.clients.publisher.api.ApiException: at org.wso2.am.integration.tests.other.APIScopeTestCase.testSetScopeToResourceTestCase(APIScopeTestCase.java:188) `

[1] - https://wso2.org/jenkins/job/products/job/product-apim/org.wso2.am$org.wso2.carbon.am.integration.backend.test/3031/testReport/junit/org.wso2.am.integration.tests.other/APIScopeTestCase/testSetScopeToResourceTestCase/

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.2.0-alpha

**Comment by RakhithaRR** [comment]
It seems both `testSetScopeToResourceTestCase` and `testCopyApiWithScopes` are failing due to the swagger parser upgrade. Both these test cases have a step where the existing swagger definition is updated with a new one. These definitions in the tests cases are incorrect and those errors can be seen when we import that to the online swagger editor as well.

Old swagger parser must have had a bug in the swagger 2.0 flow which has caused these issues to be hidden until now. The tests failed since the new parser detected the erroneous definitions in the swagger PUT step.

**Comment by rmsamitha** [comment]
Possible that this same root cause affects https://github.com/wso2/api-manager/issues/1294 too.

**Comment by rmsamitha** [comment]
Identified the root cause is same in #1294 and fixed so.
