### ISSUE TITLE
[MSSQL] Database deadlock when creating API product using 2 resources with policies

### ISSUE THREAD

**Issue by binodmx** [wso2/api-manager#1309]
### Description

APIM runs into a database deadlock scenario when it is setup with MSSQL and creating API product using 2 resources with operational policies. The steps to reproduce this issue are given below.

There won't be any errors in the UI or in the console. None of the db commands will work in the server after that point (if you go to the landing page and try to go in to an API, the UI will keep loading infinitely). Only option in this scenario is to restart the server. Note that we came across this issue while doing some migration testing.

### Steps to Reproduce

1. Take the latest release APIM 4.2.0 (alpha).
2. Setup MSSQL as the database.
3. Create an API with at least 2 resources.
4. Add an operation policy for each resource and save the API.
5. Create an API Product using the 2 resources of that API.

### Affected Component

APIM

### Version

4.2.0

### Related Issues

https://github.com/wso2/api-manager/issues/618

**Comment by chamikasudusinghe** [comment]
Date: 01 February 2023

Update: Working on reproducing the issue in the local environment (Mac M1)

**Comment by rmsamitha** [comment]
@binodmx Is this a DB deadlock? How did we ensure it?
Or the UI is blocked at some call?
Did you debug and see which DB query is causing the deadlock, else can you please do since this is already reproduced in your setup.

**Comment by chamikasudusinghe** [comment]
Date: 2nd February 2023

Update: The issue was reproduced in Ubuntu 18.04. 

Behavior: This happens when we try to create an API product with two API resources which have operation policies. After the process fails, when we try to open the previously created APIs, they keep loading.

DB Query: SELECT AUM.HTTP_METHOD, AUM.AUTH_SCHEME, AUM.URL_PATTERN, AUM.THROTTLING_TIER, AUM.MEDIATION_SCRIPT, ARSM.SCOPE_NAME, AUM.API_ID FROM AM_API_URL_MAPPING AUM LEFT JOIN AM_API_RESOURCE_SCOPE_MAPPING ARSM ON AUM.URL_MAPPING_ID = ARSM.URL_MAPPING_ID WHERE AUM.URL_MAPPING_ID = @P0

**Comment by binodmx** [comment]
@rmsamitha Yes, AM_API table cannot be accessed after executing the above scenario. The same behaviour is reported in https://github.com/wso2/api-manager/issues/618 for APIs after adding multiple operation policies.
