### ISSUE TITLE
An error occurs when API product changed to a custom life cycle state

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1367]
### Description

When a custom lifecycle status is added it is appeared in  API product lifecycle. 
But an error occurs when API product state changed to the custom state.

<img width="1458" alt="Screenshot 2023-02-01 at 12 02 56" src="https://user-images.githubusercontent.com/54719880/215968855-b2d1d446-cffe-4658-86d2-4fe2299355c9.png">

Once the error occurred , product screen  keeps loading and cannot access the page.

<img width="1458" alt="Screenshot 2023-02-01 at 11 18 07" src="https://user-images.githubusercontent.com/54719880/215969274-7ef9b9e4-c18c-4a9a-b8e0-96d95d420ac9.png">

### Steps to Reproduce

1. Add custom lifecycle state via Advanced configurations in Admin portal
2. Navigate to Publisher portal
3. Create an API product and publish
4. Change the life cycle state to custom state

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

Distributed setup and Local Environment (Mac Monterey version 12.3.1 - M1 chip)

### Relevant Log Output

Error log:

<img width="1458" alt="Screenshot 2023-02-01 at 11 50 30" src="https://user-images.githubusercontent.com/54719880/215969636-3aeda7d3-5cf3-4a00-ad92-835ed93e5bb6.png">

_No response_

**Comment by msm1992** [comment]
In APIs we manage the lifecycle state as a string[1]. However in API Products we manage the lifecycle status as an enum[2]. Therefore we get the above error while trying to associate an API Product with a custom lifecycle state. I have fixed this issue by definfing API Product's lifecycle state as a string with PRs [3] and [4].

Also note that this issue is there in APIM 4.1.0 as well and need to be fixed there as well.

[1]. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml#L8600-L8605
[2]. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml#L9278-L9289
[3]. https://github.com/wso2/carbon-apimgt/pull/11834
[4]. https://github.com/wso2/product-apim/pull/13125
