### ISSUE TITLE
Fix SMB2 test failures on public & 4.1.0 jenkin jobs

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/api-manager#1449]
### Description

The following SMB2 test cases are failing in the master & 4.1.0 branches. Need to fix them.

- SMB2FileTransferResumingTestCaseAfterConnectionFailureToSambaServer

- SMB2FileTransferResumingTestCaseWithMultipleProxyAfterConResetNServerReset

### Steps to Reproduce

Run SMB2 tests on jenkins.

### Affected Component

MI

### Version

4.2.0

**Comment by malakaganga** [comment]
Update:
I have analyzed all the codes we have ported to fix smb2 issues but seems the porting is done fine. But in 4.1.0 n master 2 tests related to resuming after ConnectionFailure (partial) are failing. But in 6.6.0 the same tests are passing.
So now I am creating a local setup and trying to mimic the behavior since it'll be easy to mimic and debug.

Thanks,
Malaka

**Comment by malakaganga** [comment]
Update:

Locally tested and running the test suite after a possible fix will update the master branch when tests are getting passed.

Thanks,
Malaka

**Comment by malakaganga** [comment]
On leave today due to a doctor's appointment.

**Comment by malakaganga** [comment]
Update:
Master build was success:
https://wso2.org/jenkins/job/products/job/micro-integrator/1869/

![Screenshot from 2023-02-20 06-55-40](https://user-images.githubusercontent.com/8380732/219989008-24f4f645-4c1c-487b-aa4d-b8b1942024dd.png)

Waiting for 4.1.0.x-full build when its success will close the issue

**Comment by malakaganga** [comment]
Update:
the wso2mi-4.1.0.x-full build was a 
![Screenshot from 2023-02-20 19-21-12](https://user-images.githubusercontent.com/8380732/220126431-0e6fde82-3e9b-4dde-b73c-3eb346f2a6c4.png)
success as well.

Hence closing the issue
