### ISSUE TITLE
Error when loading new tenant

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1505]
After creating a new tenant and login into it following error log get printed. It is not a blocker, yet printing an error log is wrong.

```
[2023-02-24 10:21:45,137] ERROR - TenantServiceCreator Error while copying API manager specific synapse sequencesjava.nio.file.NoSuchFileException: /home/dushani/wso2/Rnd/4.2.0/kernel_release/wso2am-4.2.0-SNAPSHOT/repository/tenants/1/synapse-configs/default/sequences/main.xml
```

**Comment by chanikag** [comment]
This is fixed by https://github.com/wso2/carbon-apimgt/pull/11901

This issue happens for the first tenant load only.
The TenantSynapseConfigHierarchyCreator threads are spawned twice by 
1. File authFailureHandlerSequenceNameFile = new File(filepath.toString());
            //Here we will check authfailurehandler sequence exist in synapse artifact. If it is not available we will create
            //sequence synapse configurations by using resource artifacts
            if (!authFailureHandlerSequenceNameFile.exists()) {
                createTenantSynapseConfigHierarchy(synapseConfigDir, tenantDomain);
            }
https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java#L124

2.             File graphqlFailureHandlerSequenceNameFile = new File(graphqlFilepath);
            if (!graphqlFailureHandlerSequenceNameFile.exists()) {
                createTenantSynapseConfigHierarchy(synapseConfigDir, tenantDomain);
            }
https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java#L132

Therefore, when the file already exists the error is thrown. As this is harmless, the exception is ignored.
