### ISSUE TITLE
Cannot run MI, MI Dashboard and SI on windows as a Service with Java 17

### ISSUE THREAD

**Issue by DinithHerath** [wso2/api-manager#1506]
### Description

Cannot run MI, MI Dashboard and SI on windows as a service with Java 17 and Java 17 compatible yajsw-stable-13.05.

### Steps to Reproduce

1. Setup yajsw-stable-13.05 (support java 17)
2. Follow the documentation for each product and configure "wrapper.conf" accordingly.
3. Start the wrapper

### Affected Component

MI

### Version

4.2.0-beta

### Environment Details (with versions)

Windows 11

### Relevant Log Output

```shell
INFO|wrapper|WSO2 Carbon|23-02-22 14:14:57|stopping process with pid/timeout 10428 45000
INFO|wrapper|WSO2 Carbon|23-02-22 14:14:58|process exit code: 1
system.env 58
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|started process with pid 5480
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|Shutting down Wrapper
```

**Comment by SavinduDimal** [comment]
### Micro Integrator

- Added the fixes to the `wrapper.conf` from https://github.com/wso2/micro-integrator/pull/2878.
- Tested the functionality on both Java 11 and Java 17 with YAJSW 13.05 on Windows 10.
- Updated the documentation from https://github.com/wso2/docs-apim/pull/6766.

### Streaming Integrator

- Following warn log was observed in the console when we try to use `runConsole.bat` from the wrapper.
```
org.ops4j.pax.logging.pax-logging-api [log4j2] WARN : Configuration file '..\..\conf\server\log4j2.xml' is not available. Default configuration will be used.`
```
- Due to this `DEBUG` logs were enabled for the SI server.
- However SI functionalities were tested successfully for both Java 11 and Java 17 with YAJSW 13.05 on Windows 10.
- Updated the documentation from https://github.com/wso2/docs-apim/pull/6774.
