### ISSUE TITLE
[Continuation] Make the Crypto Provider configurable

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/api-manager#1616]
### Problem

This issue is created to track the progress of Make the Crypto Provider configurable [1] for APIM 4.2.1 release.

[1] https://github.com/wso2/api-manager/issues/1219

### Solution

The usages where the org.bouncycastle.jce.provider.BouncyCastleProvider is hardcoded should be configurable along with the "BC" string which is passed as the crypto provider for different usecases.

### Affected Component

APIM

### Version

4.2.1

**Comment by HeshanSudarshana** [comment]
Hi all,

Please note that the code side changes are done and the scripts are added through the PRs. The documentation to enable and disable FIPS compliance should be added. 

Keeping this open until the PRs are merged.

Thanks,
Heshan

**Comment by shnrndk** [comment]
### Update 28/06/2023

- PRs were made to the wso2-support/carbon-multitenancy repo and the wso2-support/carbon-kernel repo. Fix has been checked in the local setup. 
- There was a problem in the fips.sh, it gives errors when it runs on the mac os. This is because this script was not tested on mac os before. Therefore I have changed this script to work on the mac os also. And I have checked this same script can be use for ubuntu. It is running on ubuntu also. 
- Therefore single fips.sh is sufficient for both OS. The patch has been made right now. And it is now moved to staging. I have checked the FIPS compliance in the staging pack. It is working without errors.

**Comment by HeshanSudarshana** [comment]
Hi @udith6415,

The changes were ported to APIM 4.2.0 and the PRs are sent for APIM 4.3.0 release.

Thanks,
Heshan
