### ISSUE TITLE
Read only user cannot view policies page

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1891]
### Description

**Current Behavior**

An error occurs as  " Error occurred while retrieving policy" when read only user access policies page.  According to the logs it seemed that read only users scope is set for policies.

This worked properly after adding internal/observer role was set to the apim:common_operation_policy_view in adavanced configurations. 

Currently 'Add new policy' button is active for read only users

**Desired behavior**

Read only user should be able to view api policies. 

'Add new policy' button should be disabled for read only users

<img width="1204" alt="Screenshot 2023-06-01 at 16 32 08" src="https://github.com/wso2/api-manager/assets/54719880/70c8cabe-6178-4103-b380-741bfb0c818d">

### Steps to Reproduce

prerequisites: create an API 

1. Log in to the publisher portal as a read only user
2. Navigate to API -> policies

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

Local Environment

**Comment by BiyonFernando** [comment]
This error is fixed in 4.3.0 version. In API manager 4.3.0 read only users cannot save any changes to the polices they make.   This behaviour can demonstrate by logging to the portal as a read-only user as bellow.
<img width="1717" alt="Screenshot 2024-07-17 at 10 28 18" src="https://github.com/user-attachments/assets/febdf710-20cc-488a-82d7-f3effcfa58b3">
