### ISSUE TITLE
Error to login on Dev Portal and Publisher

### ISSUE THREAD

**Issue by DamithHarshanaS** [wso2/api-manager#2003]
### Description

The below issue is observed when trying to log in to the APIM 4.2.0 dev and publisher portals. 

```
ERROR - [idp] Servlet.service() for servlet [idp] in context with path [/publisher] threw exception

java.io.IOException: An exception occurred processing [/services/login/idp.jsp] at line [88]

85:        System.out.println(settingsAPIUrl);
86:        out.println(settingsAPIUrl);
87:
88:   HttpResponse<String> settingsResult = client.send(getSettingsReq, HttpResponse.BodyHandlers.ofString());
89:
90:   HttpRequest getCatalogReq = HttpRequest.newBuilder()
91:       .uri(URI.create(serviceCatalogSettingsAPIUrl))
Caused by: java.io.IOException: No name matching localhost found
```
To resolve this issue without adding a SAN entry,  modified "app.origin.host" value in the "settings.json" file located at "repository/deployment/server/webapps/publisher/site/public/conf/settings.json" with the custom hostname and added the below configuration to the toml file. 

```
[server]
internal_hostname = "<hostname>"
```

 
However when using a load balancer then can observe the below error. Caused by: java.net.ConnectException: Connection refused

```
 at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]

  at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:?]
    at jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(Unknown Source) ~[java.net.http:?]

at jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source) ~[java.net.http:?]

   at jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source) ~[java.net.http:?]

    at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
```

Therefore if the internal_hostname config is there, the host should be getting from the internal_hostname and removing the port.

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.2.0

**Comment by GihanAyesh** [comment]
Since the concern is adding the "localhost" as the SAN entry in their custom JKS, we can suggest to use a custom hostname instead of localhost in their custom JKS.

Then add the custom hostname as below
```
[server]
internal_hostname = "custom_host_name"
```
Then change the custom hostname in the `repository/deployment/server/webapps/publisher/site/public/conf/settings.json`

Please note that the proxy host can't be used as the internal_hostname since we cannot give the accessibility of internal calls to the outside.

The accessibility to custom_host_name:mgtTransportPort(9443) port should be available too.
