### ISSUE TITLE
Add a content-security-policy for UI portals

### ISSUE THREAD

**Issue by Avishka-Shamendra** [wso2/api-manager#2062]
### Problem

Not having a Content Security Policy (CSP) header exposes webapps to security risks, as it allows malicious actors to execute harmful scripts or attacks, such as cross-site scripting (XSS). More information about the benefits of having a CSP can be found in [1] [2]

[1] - https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
[2] - https://content-security-policy.com/

### Solution

Add a CSP header for UI portals (publisher, devportal and admin portal)

### Affected Component

APIM

**Comment by dushaniw** [comment]
Config to support custom headers are added with https://github.com/wso2/api-manager/issues/1272. Due to limitations in current JSP webapps and breaking changes that needed to be implemented in React UI apps, we will not be addressing this in current versions. Addressing this needs considerable design changes in both APIM components and identity webapps. Hence closing the issue for now.
