### ISSUE TITLE
Login with PRIMARY/ domain to the Devportal does not allow to generate application Keys

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/api-manager#2107]
### Description

After login to the Devportal with Primary/SuperAdminUser to the devportal, tried to generate OAuth ConsumerKey and Secrets for the defaultApplication and for the other applications, then observed an exception at the UI and could observe an error in the carbon.log file.

### Steps to Reproduce

- Log in to the Devportal with PRIMARY userdomain
  - example:
      - username: PRIMARY/admin
-Login got success
-Then go to applications and tried to generate the keys for Default Application and other applications and got the same error.

### Affected Component

APIM

### Version

4.0.0

**Comment by hisanhunais** [comment]
- In the master branch pack, when logging into the Devportal using PRIMARY/admin, it uses the username as admin (Drops the PRIMARY).
- Hence, the SP name becomes admin_<APP_ID>_PRODUCTION which generates keys successfully.
- As a result, this issue is not reproducible in the master branch pack.
- Hence, closing the issue
