### ISSUE TITLE
Log4j 2.15.0 CVE-2021-45046

### ISSUE THREAD

**Issue by ekhv** [wso2/api-manager#2126]
### Description

Security scanner highlighted the critical security risk with transitive log4j dependency.

It was found that the fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was incomplete in certain non-default configurations. This could allows attackers with control over Thread Context Map (MDC) input data when the logging configuration uses a non-default Pattern Layout with either a Context Lookup (for example, $${ctx:loginId}) or a Thread Context Map pattern (%X, %mdc, or %MDC) to craft malicious input data using a JNDI Lookup pattern resulting in an information leak and remote code execution in some environments and local code execution in all environments. Log4j 2.16.0 (Java 8) and 2.12.2 (Java 7) fix this issue by removing support for message lookup patterns and disabling JNDI functionality by default.

Please fix it.

### Affected Component

APIM

### Version

4.2.0

### Suggested Labels

log4j

**Comment by AnuGayan** [comment]
@ekhv please be advised that security issues must be reported to [security@wso2.com](mailto:security@wso2.com), not as a GitHub issue, in order to reach the proper audience. We strongly advise following the [WSO2 Security Vulnerability Reporting Guidelines](https://security.docs.wso2.com/en/latest/security-reporting/vulnerability-reporting-guidelines/) when reporting the security issues.

Furthermore, this has been addressed and released as an update for the enterprise customers and mitigated in the latest product releases.
