### ISSUE TITLE
Apictl tool issue with enabling the APIM hashing

### ISSUE THREAD

**Issue by jithma95** [wso2/api-manager#2307]
### Description

Tested the some apictl commands as per the customer issue and getting some errors with the apictl tool.The APIM version is 4.0.0 and the apimctl tool version is 4..0.4. We have tested the below command with enabling the OAuth2 token hashing to protect OAuth2 keys according to the customer cenario. To enable the token hashing, the below config is added to the deployment.toml file.

[apim.oauth_config]
enable_token_hashing = true

Using the apictl tool tool performed the get command at first time the “./apictl get apis -e dev -k --verbose” command is given the results without any issues. But on the second attempt it will fail.

### Steps to Reproduce

To create the environment -: dev :
./apictl add env dev --apim https://localhost:9443/

To login to the dev environment :
./apictl login dev -u admin -p admin -k --verbose

Get apis from the environment -:
./apictl get apis -e dev -k --verbose

### Affected Component

APICTL

### Version

4.1.0

**Comment by YasasRangika** [comment]
Quoted from internal discussion:
As per our analysis, clientId and clientSecret are given to a particular user only once when token hashing is enabled, and they are saved in the keys.json file. The saved entry is deleted when the user logs out. If the user wants to log in again, [1] is returned from the DCR endpoint, and APICTL saves the BASE64 encoded value of it in the keys.json file as the clientSecret value.

When the user attempts operations such as "apictl get apis -e dev -k --verbose," the BASE64 encoded value of [1] is used as the clientSecret, causing these problems. However, this behaviour is expected when token hashing is enabled because, according to [2], we must copy and save it for later use.

Solution

After logging into the system for the first time using a particular user credential, content related to the user in the keys.json should be backed up. When attempting to log into the system using the same user, the backed-up content should be mounted to the keys.json file under the user-related content.

[1] "{"hash": "Some Value", "algorithm": "SHA-256"}"
[2] The Consumer Secret value is displayed in plain text only once. Therefore, be sure to copy and save it for later use. ( Source: https://is.docs.wso2.com/en/latest/guides/access-delegation/oauth-token-hashing/#configure-the-service-provider )
