### ISSUE TITLE
An error occurs when a user with an 'internal/publisher' role trying to publish an API product

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2473]
### Description

Following error occurs when a user with an internal/publisher role trying to publish an API product.

<img width="1170" alt="Screenshot 2024-02-13 at 10 36 47" src="https://github.com/wso2/api-manager/assets/54719880/2135ca11-f7cf-47ea-b0e4-0cde11ca328e">

No server logs are generated for the issue.

### Steps to Reproduce

1. Login to publisher portal from a user with 'internal/publisher' role
2. Navigate to the left menu and select API products
3. Add details and click on 'Next'
4. Add resources
5. Click on 'Create & publish' button

### Affected Component

APIM

### Version

4.2.0 , 4.3.0-M1

### Environment Details (with versions)

Local Environment
Mac OS

**Comment by chamilaadhi** [comment]
Seems there are some additional behaviours noticed while going through the issue
- After the issue happens, go to the deployment section and manually create a deployment and you could publish the product
- After that, above issue is not happening for any other newly created api products using the wizard
- Error again happens if you log out and login
