### ISSUE TITLE
Searching APIs using custom properties not working

### ISSUE THREAD

**Issue by O-sura** [wso2/api-manager#2552]
### Description

According to the [APIM docs](https://apim.docs.wso2.com/en/4.3.0/design/create-api/adding-custom-properties-to-apis/#search-using-custom-properties), after adding an additional property for an API, it should be possible to search for an API using <property_name>:<property_value> but it shows as no matching records found when searched.

### Steps to Reproduce

1. Create an API in APIM
2. Go to Properties > Add New Property(Ex: "env" as the Property Name and "sandbox" as the value) and then Save it.
![Screenshot from 2024-03-01 16-45-23](https://github.com/wso2/api-manager/assets/84634723/ac5c6a21-419b-4f33-a7f2-ba86bd23ec23)

3. Go to Publisher Portal Homepage
4. Search for "env:sandbox" in the searchbar
![Screenshot from 2024-03-01 16-45-43](https://github.com/wso2/api-manager/assets/84634723/a1610226-0a8f-4ba5-bb80-c94381b89cb7)

### Affected Component

APIM

### Version

4.3.0

**Comment by RakhithaRR** [comment]
The searching works as expected in devportal. When devportal visibility is enabled for a property, it is saved in registry as `<property_name>__display`. Due to this, when searching from Publisher, we need to search it in the following manner.

```
<property_name>__display:<property_value>
```

For example, if we added a property called `env` with value `dev`, we need to search it in the publisher as `env__display:dev`. This will return the results.

This is a known limitation in APIM and cannot be fixed. Hence closing this issue.
