### ISSUE TITLE
401 unauthorized error occurs when invoking an API in developer test console using apikey

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2564]
### Description

When attempting to invoke an API using an API key token through the developer test console, the request fails with a 401 Unauthorized error.  The request header is incorrectly including an authorization bearer as the token instead of the selected API key token.

This functionality is verified in the 4.2.0 version and it's working properly.

### Steps to Reproduce

Prerequisites
--------------
Deploy the sample pizzashack API in publisher and select apikey for application level security.

1. login to developer portal
2. Create an application and generate apikey token
3. Navigate to test console
4. Invoke the API using apikey.

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
The same issue happens when trying to invoke an API using an APIKey through the Developer portal swagger console. The invocation works through the curl command or any other rest api client. The reason is because the Authorization Bearer header is incorrectly appended to the request instead of the APIKey header in the swagger console of the Developer portal. This needs to be fixed.
