### ISSUE TITLE
Invalid/incorrect URLs in Documents UI, OpenAPI/Swagger definition, and Postman collection for third-party APIs

### ISSUE THREAD

**Issue by Aklesk** [wso2/api-manager#2601]
### Description

When publishing an API and marking it as "third-party" to WSO2 API Manager, some components which need URLs for the API use the nonexistent vHost and context, rather than the external API endpoints that must be provided when marking an API as "third-party".

This leads to invalid URLs displayed for the `API Base URL` on the Documentation page, and invalid data for server/auth URLs in the downloadable OpenAPI/Swagger definitions and Postman collection in the store for the affected API.

## In the WSO2AM Publisher:

Create a new API:

- Name: TestApi
- Context: test
- Version: v1

Publish.
In "Basic Info", change "Mark the API as third party" to "Yes".
Enter `https://example.com` for external endpoint(s).
Save.

In "Lifecycle", click "Publish".

## In the WSO2AM Store / Dev Portal:

View the `TestAPI` definition.
Go to `Documents`.
The displayed `API Base URL` should be `https://example.com`, but is instead `http://test/v1`.

Go to `Try Out`.
Download the Postman collection.
Examine the Postman collection via JSON viewer.
`baseUrl` variable should be `https://example.com`, but is instead `http:///test/v1`.

Go to `Try Out`.
Download the Swagger definition.
Examine the Swagger definition via JSON viewer.
URL(s) in `servers` should be `https://example.com`, but is instead `http:///test/v1`.
Under `securitySchemes`, the `authorizationUrl` for the third-party API is not known by WSO2AM, and therefore should not be specified, but it is instead `/authorize`.

### Affected Component

APIM

### Version

4.2.0

**Comment by RakhithaRR** [comment]
This has to be fixed in the following scenarios

- Generated swagger document in Documents section in the Devportal
- Postman collection
- Servers section in the downloadable swagger in Devportal

Need to further discuss how the authorize endpoint url should be shown under the security schemes in the swagger. Currently this has implicit grant as a placeholder and gateway url for the non third party scenario as well. This seems to be an incorrect approach.
