### ISSUE TITLE
Response caching not working in distributed setup

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#2654]
### Description

After enabling response caching, backend yet receives the request instead it's getting served from the cache. This only happens in the distributed setup and locally the functionality works fine.

### Steps to Reproduce

1.) Create an API
2.) Enable response caching (Set timeout to 100s)
3.) Use a mock backend such as mockoon or mockable[1]  and use that endpoint for the API
4.) Invoke the API twice.
5.) Check backend logs. It should only consist of one log.

[1] https://www.mockable.io/a/#/logger/demo4753917

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
The reason for response caching not working in the distributed setup is because backend jwt is enabled in the gateway node.

      [apim.jwt]
      enable = true

This creates an additional `X-JWT-Assertion` header which changes for every request. As a result, caching does not work. (Headers and body need to be same to cache and server back)
