### ISSUE TITLE
Admin Cannot login to portals when the password is updated

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2703]
### Description

Admin Cannot login to portals when the password is updated

### Steps to Reproduce

1. Login ad admin to devportal
2. Select logout 
3. select change password option 
4. Update password
5. Try to login again

### Affected Component

APIM

### Version

4.3.0-alpha

### Relevant Log Output

```shell
When logging into devportal

[2024-03-22 16:29:52,272] ERROR - introspect_jsp {
  "traceId": "67739db5-ecc2-42f6-a2f8-b80f02033f01",
  "code": 401,
  "description": "Authorization failure. Authorization information was invalid or missing from your request.",
  "message": "Unauthorized"
}
```

**Comment by RakhithaRR** [comment]
This is the expected behaviour in the product and this behaviour is there in previous APIM versions as well. If the super admin password needs to be changed, you need to follow the steps in [1].

[1] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/
