### ISSUE TITLE
[APIM][3.2.0]Null pointer exception when throttle_decision_endpoints protocol set to ssl.

### ISSUE THREAD

**Issue by ShehanRavindu** [wso2/api-manager#2810]
### Description

There is a null pointer exception getting hidden when the throttle_decision_endpoints protocol is set to **ssl** instead of **tcp**, resulting in another null pointer exception.

### Steps to Reproduce

1. Open the deployment.toml file.
2. Change the throttle_decision_endpoints to SSL under [apim.throttling]
3. Retsart the server.
4. Do a token generation request.

### Affected Component

APIM

### Version

3.2.0

**Comment by AnuGayan** [comment]
This has happened due to a misconfiguration. Using the following sample configuration, this can be mitigated

[apim.throttling]
enable_advanced_throttling = true
enable_data_publishing = true
enable_policy_deploy = true
service_url = "https://localhost:9443/services/"
throttle_decision_endpoints = ["tcp://localhost:8672"]

[apim.throttling.jms]
ssl = true

#traffic manager
[broker.transport.amqp.ssl_connection]
enabled = true
port = 8672
ssl_enabled_protocols = "TLSv1,TLSv1.2"
ciphers = "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
