### ISSUE TITLE
Search and edit capability to Micro Integrator dashboard

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#352]
### Problem

Currently, there is no search operation available to search the deployed artifacts from the MI monitoring dashboard. This is a much-needed feature for complex applications. 

Furthermore, Sometimes in order to make a quick fix for some issue, we are making small configuration changes directly from the EI console and later include those changes in the carbon applications in the next deployment. Therefore, please check the possibility of providing the artifacts editing feature from the MI dashboard as well.

### Solution

1. Providing the search option from the MI dashboard
2. Provide the edit option from the MI dashboard 

### Affected Component

MIDashboard

**Comment by RusJaI** [comment]
hi all,
Please note that since the dashboard is only for read only purposes and it's recommended to edit the artefacts over the UI,
Edit capabilities will not be provided to the dashboard.
This is mentioned in the corresponding internal as well.
https://github.com/wso2/api-manager/issues/412 this closed issue fulfils the search capability.
Hence closing this issue. 
Regards,
Rusiri
