### ISSUE TITLE
API name cannot have a empty space

### ISSUE THREAD

**Issue by lpastor74** [wso2/api-manager#398]
### Describe your problem(s)
as of now, it is not possible to create an API name with empty space in the publisher.
Sometimes API names consist of two words and the only option is to use the Camile style with is not very esthetic.
 
### Describe your solution
Can we have an API and addition parameters like '**display name**' and use that in DevPortal?
The name will be still used for uniqueness but **display name** would be used in DevPortal

**Comment by shnrndk** [comment]
### Update 27/10/2023

- Checked the feasibility of including spaces to the API name and Changing the API provider.
- Created feasibility doc[1].
- There were some issues happened in both of these tasks, which were explained in this doc [1].
- On 20/10/2023 had a meeting with Sanjeewa, Nandika, Dushani and Thilini regarding this issues. And suggested me to keep looking for the solutions for these issues.
- For the search issues when we are search in publisher portal when including the spaces in api name, we are using "%20" instead of search in the backend.
- To api provider change manually, these things needs to done.
    1. Change the Api provider artifact in the registry for that API.
    2. Change the api provider path, by renaming/changing the name of the api provider root folder.
    3. Change the api provider name in the AM_API table in the db.
- The various problems  have arose by using steps.
    1. The APIs did not appeared in the publisher portal as well dev portal.
    2. The total api count in the publisher portal was wrong.
- After having several discussions with Prasanna we have found that, there is method written in the registry, ```registry.move()``` . By using this method we can easily change the path. For example
```
registry.move("/_system/governance/apimgt/applicationdata/provider/admin/PizzaShackAPI/1.0.0/api",
                "/_system/governance/apimgt/applicationdata/provider/sahan/PizzaShackAPI/1.0.0/api");
```
to
```
registry.move("/_system/governance/apimgt/applicationdata/provider/admin/PizzaShackAPI/1.0.0/swagger.json",
                "/_system/governance/apimgt/applicationdata/provider/sahan/PizzaShackAPI/1.0.0/swagger.json");

```
- After using this method, all of the issues occurred when changing api provider name were disappeared. 
- Therefore i concluded that these are tasks feasible to continue.
- Next week I am hoping to implement these features.
- Started to create the design doc.[2]
[1] https://docs.google.com/document/d/1GfA81SP1JWfQGWyNsWtFz0Gv2BDTvlxIovFp4f8kHRw/edit
[2] https://docs.google.com/document/d/1xOo3vGUzTEm2A46UthkWA3xsjVtSgziREc-ebrpAJPE/edit

**Comment by shnrndk** [comment]
### Update 10/11/2023

- When checking the feasibility of including spaces to the API name, Tharika mentioned me to check with APICTL imports and exports when there is api name with with spaces.
- This was previously disallowed by this PR: https://github.com/wso2/carbon-apimgt/pull/8305/files
- But we can't find the codelines which were changed  by this PR, in the 4.2 branch and the master branch.
- Checked the APICTL imports and exports when there is api name with with spaces.
- When exporting we need to include the api name in spaces.
```apictl import api -f "./Test API 123" -e production ```
When importing we can have \ symbol between space or use "".
Ex:- 
```./apictl import api -f "dev/Test API 123_1.0.0.zip" -e dev```
```./apictl import api -f dev/Test\ API\ 123_1.0.0.zip -e dev```
- Started to implement the api provider name change feature
- Added the method `changeApiProvider()` in the RegistryPersistenceImpl.java, In this method the logic is
        1.) First move the registry path to the new api provider
        2.) Then change the API provider artifact in the new registry provider path
- There was an issue occured when testing the new implementation, the apis doesn't display properly in the publisher portal and the devportal.
- But in the debug mode this error wasn't occured.  I think the reason for this issue is, after moving to registry to new api provider, it needs some seconds to reindex, then only we can change the API provider artifact. I have put the thread.sleep(5000) in the middle of these 1 and 2 steps, then this issue wasn't occured.
- This issue was discussed with Arshadh and Prasanna. There were several solutions have tested but all of these were failed. Tharindu mentioned that we do not need to change the path to change the api provider name. Currently testing this new approach.
- This week I am on annual leave, next week hoping to conclude the design and start to implement the design in the new approach.

**Comment by shnrndk** [comment]
Change Api Provider PR: https://github.com/wso2/carbon-apimgt/pull/12189
Enable to create APIs with spaces: https://github.com/wso2/carbon-apimgt/pull/12187
UI PR: https://github.com/wso2/apim-apps/pull/519
Doc PR: https://github.com/wso2/docs-apim/pull/7467
Intergration Test PR: https://github.com/wso2/product-apim/pull/13304

**Comment by shnrndk** [comment]
### Update 18/12/2023

- Tested the reasons for the failures.
- The test failures occurred because the newly added scopes were not included in the tenant.confs within the product-apim repo.

**Comment by npamudika** [comment]
Need to merge the 3 PRs after getting the review comments resolved and approved - https://github.com/wso2/product-apim/pull/13304, https://github.com/wso2/apim-apps/pull/519, https://github.com/wso2/carbon-apimgt/pull/12200

**Comment by lpastor74** [comment]
Do we have a plan to release the patch for the 4.2 version?
