### ISSUE TITLE
Upgrade HTTP Core with the Fixes done

### ISSUE THREAD

**Issue by Nirothipan** [wso2/api-manager#400]
### Description

$subject

We've forked HTTP Core and done several fixes, but these are not available in master. Need to upgrade to latest apache http core version with the fixes or fork and use this in master.

### Affected Component

APIM

### Version

4.2.0

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/142

**Comment by sajinieKavindya** [comment]
Since the latest org.apache.httpcomponents:httpcore-nio:4.4.15 release, several fixes have gone to the Apache httpcore-nio-4.4.x branch. Until the 4.4.16 version is released in apache/httpcomponents-core repo, we have decided to fork the latest 4.4.x branch of apache/httpcomponents-core to [4.4.15-x branch](https://github.com/wso2/wso2-httpcore-nio/tree/4.4.15-x) in wso2/wso2-httpcore-nio repo. 

Accordingly, the following tasks were carried out:

1. The current master branch was copied to the 4.3.3-x branch.
2. The latest 4.4.x branch of apache/httpcomponents-core was forked to [4.4.15-x branch](https://github.com/wso2/wso2-httpcore-nio/tree/4.4.15-x).
3. The version [4.4.15-wso2v2](https://github.com/wso2/wso2-httpcore-nio/tree/v4.4.15-wso2v2) was released from the 4.4.15-x branch and the relevant components were updated to use this new dependency accordingly.

**Comment by sajinieKavindya** [comment]
Apache HttpCore NIO 4.4.16 has been released [1]. Therefore, APIM-4.2.0 and related components will be updated to use this direct dependency org.apache.httpcomponents:httpcore-nio:4.4.16 and the associated orbit [2]. Also, since there will be no usage for version 4.4.15-wso2v2, it will be dropped in near future.

[1] - https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore-nio/4.4.16
[2] - https://github.com/wso2/orbit/pull/863
