### ISSUE TITLE
DOM-Based XSS in callback parameter on Recover Password site

### ISSUE THREAD

**Issue by micro-jr** [wso2/api-manager#442]
### Description

Hello, 
we have found DOM-Based XSS in callback parameter on Recover Password site.

### Steps to Reproduce

you must call: /accountrecoveryendpoint/recoverpassword.do?usernameUserInput=lk_priv&username=lk_priv&tenantDomain=carbon.super&isSaaSApp=false&recoveryOption=EMAIL&callback=javascript%253aalert(1)

on the next step click Cancel - you have popup javascript alert.

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

we use docker file: wso2/wso2am:4.1.0-alpine

### Suggested Labels

xss security bug

**Comment by chamilaadhi** [comment]
Hi,

This can be fixed by following the instructions that have been given in our documents. For more information please refer [1][2][3].

[1] https://docs.wso2.com/display/Security/Security+Advisory+WSO2-2021-1314
[2] https://is.docs.wso2.com/en/5.11.0/administer/product-level-security-guidelines/#callback-url-regular-expressions
[3] https://is.docs.wso2.com/en/5.11.0/learn/password-recovery/
