### ISSUE TITLE
OpenTelemetry support 

### ISSUE THREAD

**Issue by tharindu1st** [wso2/api-manager#65]

**Comment by Rashmika998** [comment]
Since both OpenTelemetry and OpenTracing(deprecated) are available now, to differentiate them these are the configurations that needs to be added in deployment.toml file,

**OpenTracing for Jaeger,** 

[apim.open_tracer]
remote_tracer.enable = true
legacy = true
remote_tracer.name = "jaeger"
remote_tracer.properties.hostname = "localhost"
remote_tracer.properties.port = "6831"

**OpenTracing for Zipkin,**

[apim.open_tracer]
remote_tracer.enable = true
legacy = true
remote_tracer.name = "zipkin"
remote_tracer.properties.hostname = "localhost"
remote_tracer.properties.port = "9411"

**OpenTelemetry for Jaeger,**

[apim.open_tracer]
remote_tracer.enable = true
remote_tracer.name = "jaeger"
remote_tracer.properties.hostname = "localhost"
remote_tracer.properties.port = "14250"

**OpenTelemetry for Zipkin,**

[apim.open_tracer]
remote_tracer.enable = true
remote_tracer.name = "zipkin"
remote_tracer.properties.hostname = "localhost"
remote_tracer.properties.port = "9411"
