### ISSUE TITLE
API without Security can be invoked from Devportal without signing in  - however The access token message is still on screen

### ISSUE THREAD

**Issue by robbla** [wso2/api-manager#881]
### Description

When you create an API WITHOUT Security, the API can be invoked from the Devportal, however the screen still shows a message 
![image](https://user-images.githubusercontent.com/11582659/199444340-b57e867c-232b-47ce-9049-416c9bdd7f02.png)

I do not need to log in , nor do i need to subscribe or even supplu a token

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/11582659/199443987-ae899e42-173d-42a7-a108-34c0423d8018.png)

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

regular Linux Centos env

### Relevant Log Output

```shell
None
```

### Related Issues

None

**Comment by GihanAyesh** [comment]
As you said, this scenario happens when no security is applied to the invoking API resources. Usually, the API end user does not know the security information of the API resources, which is only decided by the API creator at the time of API creation. Hence, this is a generic message shown to the end user. However, showing the warning icon in the notice can be misleading for APIs without security. So the warning icon is changed into an info icon.

**Comment by GihanAyesh** [comment]
Added the PR https://github.com/wso2/apim-apps/pull/406 to change notice icon

**Comment by GihanAyesh** [comment]
Please comment if you request further clarification. Closing the issue
