### ISSUE TITLE
Configure a Distributed deployment for Testing purpose

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#957]
### Description

A distributed deployment should be created for Release testing purposes.

### Affected Component

APIM

**Comment by GihanAyesh** [comment]
- [ ] Set up the local distribution and test
- Create a build with control plane and gateway worker with MySQL db
- [ ] Fork the ansible-apim script
- [ ] Get necessary Azure instances
- 2 instances with 8 core, 32 GB, General purpose ( For running Profiles), 1 instance with 4 core, 8GB, Compute optimised (For running database and load balancer)
- [ ] Customize the script 
- Support Azure (instead of Amazon which was the previous service), customization for above mentioned instances 
- [ ] Run the script and host the setup
- [ ] Test the setup

**Comment by thisaltennakoon** [comment]
- [ ] Initial setup
- [ ] Configuring load balancer

**Comment by GihanAyesh** [comment]
The packs are running without the lb and working on the port matching so that the cp,gw and tm communicate with each other. Then the lb will be added to complete the setup

**Comment by thisaltennakoon** [comment]
Configured a load balancer and APIM in separate nodes and exposed the APIM using the load balancer. This method can be applied when setting up the APIM with profiles.

**Comment by GihanAyesh** [comment]
The profiles are working with the LB in place, can publish an API. Minor issue with invoking the API which is related to mapping

**Comment by GihanAyesh** [comment]
The issue with the invoking is resolved and the latest APIM pack is hosted
