### ISSUE TITLE
Carbon kernel 4.8.0 m2 release

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#973]
### Description

Carbon kernel 4.8.0-m2 should be done with the below fixes.

- [x] Hazelcast removal - https://github.com/wso2/carbon-kernel/pull/3440
- [x] Correlation support - https://github.com/wso2/carbon-kernel/pull/3412
- [x] Add missing registry indices - https://github.com/wso2/carbon-kernel/pull/3439

Carbon-kernel 4.8.0-m2 should be tested after the below fix is merged.

- [x] https://github.com/wso2/api-manager/issues/1028

### Affected Component

APIM

### Version

4.2.0-M1

**Comment by wasuradananjith** [comment]
The Carbon Kernel 4.8.0-m2 is released [1]. However, still the kernel is not bumped in APIM until the issue [2] is resolved.

[1] https://github.com/wso2/carbon-kernel/releases/tag/v4.8.0-m2
[2] https://github.com/wso2/api-manager/issues/1028

**Comment by tharikaGitHub** [comment]
**Update** : 
- Hazelcast was removed from carbon-analytics-common repo through issue https://github.com/wso2/api-manager/issues/1028. 
- The carbon-analytics-common 5.3.0 release is done. 
- After setting up the Gateway in a distributed setup another error was noticed where hazelcast was required from carbon-commons repo. 
- Hazelcast was removed from carbon-commons as well.
- Currently the setup is being tested through https://github.com/wso2/api-manager/issues/1028 so that the kernel can be bumped.

**Comment by tharikaGitHub** [comment]
APIM is now upgraded to kernel version 4.8.0-m2. The PRs are merged. Hence closing the issue.
