### ISSUE TITLE
Recover with Security Questions Option is not Working on Forgot Password

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#984]
### Problem

Even-though there are two options to change password from the login page when a user forgot the password, only "Recover with Mail" option works. If a user try to use "Recover with Security Questions Option", an exception will be thrown. 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/38649090/203023190-fa404cb3-2a0b-4cd3-92e5-059fa2f95455.png">

### Solution

If in APIM, we are not letting this option, it's better to remove this option from UI since this is misleading. Else, since this a function, we have to fix this considering this as a bug. 

### Additional Note

In order to try the Forgot Password option in APIM, you can follow [this](https://apim.docs.wso2.com/en/4.2.0/consume/user-account-management/recover-password/) documentation. 
Since it may need a minor improvement, you may also read [this](https://github.com/wso2/docs-apim/issues/6456) issue which is related to the above documentation.

### Affected Component

APIM

### Version

4.2.0-M1

**Comment by BLasan** [comment]
Hi,

Reproduced the issue and this comes out regardless of the consent we have given.
![Screenshot 2023-02-15 at 10 41 39](https://user-images.githubusercontent.com/43112139/218938780-019fa03a-3bfa-4638-982d-664446df3289.png)

**Comment by BLasan** [comment]
Hi,

This procedure is debugged and none of the configurations are getting populated with the correct ones we've given. This is due to the response code change (getting `302` instead of a `200`) after executing a POST request to `/api/server/v1/identity-governance/preferences` and then it always returns the default value of the function parameter which is `true`. Same debug was carried out for IS 6.1.0, and was getting the correct configs as expected. Also, please note that APIM uses `5.24.7` jar version and IS 6.1.0 uses the `5.25.92`.

Thanks,
Benura
